[project]
name = "transports-publics-france"
# x-release-please-start-version
version = "0.2.0"
# x-release-please-end
description = "TODO"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datagouv-client>=0.5.0",
]

[dependency-groups]
dev = [
    "black==25.1.0",
    "pytest>=9.1.1",
    "pytest-mock>=3.15.1",
]

[project.scripts]
generate-dataset = "transports_publics_france.datasets.cli:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13"]
build-backend = "uv_build"
